// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"database/sql"
)

type Session struct {
	ID        string
	UserID    string
	CreatedAt sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	CreatedAt sql.NullTime
}
